### ISSUE TITLE
ImportError: cannot import name 'environmentfilter' from 'jinja2'

### ISSUE THREAD

**Issue by Nekofoxmiu** [markus-perl/ffmpeg-build-script#184]
make[1]: Entering directory '/content/ffmpeg-build/packages/tiff-4.5.0/doc'
/usr/local/bin/sphinx-build \
-D "release=4.5.0" \
-D "version=4.5" \
-d "./cache" \
-b html \
"." "./html"
/usr/local/bin/sphinx-build \
-D "release=4.5.0" \
-D "version=4.5" \
-d "./cache" \
-b man \
"." "./man"
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.9/dist-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.9/dist-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/local/lib/python3.9/dist-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/local/lib/python3.9/dist-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/local/lib/python3.9/dist-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.9/dist-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.9/dist-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/local/lib/python3.9/dist-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/local/lib/python3.9/dist-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/local/lib/python3.9/dist-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
make[1]: *** [Makefile:810: doc-html] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:818: doc-man] Error 1
make[1]: Leaving directory '/content/ffmpeg-build/packages/tiff-4.5.0/doc'
make: *** [Makefile:570: all-recursive] Error 1

Failed to Execute make -j 2

**Comment by markus-perl** [comment]
Closing as stale. This was reported against a script version ≤1.45 and FFmpeg ≤6.0, on distributions that are themselves out of support. Every package version, download URL and patch in the build has been replaced since, and the script now builds FFmpeg 9.0. The failure is no longer reproducible in any form we can verify.

If you still hit something like this with the current release, please open a fresh issue with the full build log and your OS/compiler versions — it will get a much better answer than this thread can.
