### ISSUE TITLE
Failed to Execute pip3 install pip setuptools

### ISSUE THREAD

**Issue by IanBlakeley** [markus-perl/ffmpeg-build-script#195]
Pip3 command fails with `Failed to Execute pip3 install pip setuptools --quiet --upgrade --no-cache-dir --disable-pip-version-check` 

full errors are
```
 Traceback (most recent call last):
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 873, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.VersionConflict: (pip 23.1.2 (/home/ian/.local/lib/python3.10/site-packages), Requirement.parse('pip==20.0.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 324, in run
    session = self.get_default_session(options)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
    return select_backend().Environment.default()
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
    from . import pkg_resources
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
    from pip._vendor import pkg_resources
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3327, in <module>
    def _initialize_master_working_set():
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3301, in _call_aside
    f(*args, **kwargs)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3339, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 631, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/home/ian/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'pip==20.0.2' distribution was not found and is required by the application
```

If I manually run `pip3 install pip setuptools` then I get `Requirement already satisfied ` ergo it is already installed

**Comment by kirk29974** [comment]
apt-get install python3-pip

**Comment by IanBlakeley** [comment]
if you see my post you'll see I am running pip3 commands, ergo it is already installed

**Comment by markus-perl** [comment]
Fixed in b51a389.

Every pip call in the meson bootstrap now goes through a helper that retries with `--break-system-packages` and, if that still fails, prints a warning and continues instead of ending the run. Previously the call went through `execute()`, which exits 1 on any non-zero status, so `externally-managed-environment` aborted the whole build at that line rather than falling through to the advice printed just above it.

Please reopen if you still hit this on current master.
